[package]
name = "ne-tozi"
version = "0.1.0"
authors = ["Sebastián Magrí <sebasmagri@gmail.com>"]

[dependencies]
rocket = "0.2"
rocket_codegen = "0.2"
rocket_contrib = { version = "0.2", features = ["json"] }
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
